server:
  port:8080
spring:
  jackson:
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/timebank?serverTimezone=GMT%2b8
    username: root
    password: 2231030102
mybatis:
  mapper-locations: classpath:mapper/*.xml